### ISSUE TITLE
Build gui in Yocto

### ISSUE THREAD

**Issue by bcis93** [atharvanan1/aesd_linux_app#11]
The completed gui (see [this](https://github.com/atharvanan1/aesd_linux_app/issues/8) and [this](https://github.com/atharvanan1/aesd_linux_app/issues/9)) should be added to (and built through) our Yocto build.

DoD: gui application added to Yocto build (and the build succeeds).

Blockers: [Display/UI](https://github.com/atharvanan1/aesd_linux_app/issues/8), [Sensor integration](https://github.com/atharvanan1/aesd_linux_app/issues/9) (resolved)

**Comment by bcis93** [comment]
Added the meta-qt5 layer and the qt-app recipe to the build with [this commit](https://github.com/atharvanan1/aesd_project_build/commit/e591d1042c50c74a7d6870fa6ee09dbfe7a3da0d)

**Comment by bcis93** [comment]
A few small [bug fixes](https://github.com/atharvanan1/aesd_project_build/commit/8f709fefa5dcf6e843c13bbf7a40322158cea562)

**Comment by bcis93** [comment]
Done. The gui application builds in Yocto

**Comment by atharvanan1** [comment]
GUI runs perfectly fine. Clicking the "Get Temperature" button provides the updated temperature value.

**Comment by atharvanan1** [comment]
Resolved minor error by adding settings for QT_QPA_PLATFORM.

Code: 65ea96f0f7bb7003d68aa9a2407b6827fcf69340
