### ISSUE TITLE
Data transfer to/from cloud

### ISSUE THREAD

**Issue by bcis93** [atharvanan1/aesd_linux_app#6]
Develop a driver to send data to the cloud and receive data from the cloud. Develop an API for use by a higher level application

DoD: Driver implemented, data transfer functional, and API provided

**Comment by bcis93** [comment]
I have a basic driver written, and a simple application to test it. I am waiting on a Yocto build so that I can test it

**Comment by atharvanan1** [comment]
Yocto build is ready. Just add a recipe into layers/meta-st/meta-aesd-project using devtool, and additionally refer to [Board Support Document](https://github.com/cu-ecen-5013/final-project-atharvanan1/wiki/STM32MP1-Board-Support-Package) -> Add custom application section for detailed information

**Comment by bcis93** [comment]
Driver is implemented and API provided in .h file. Using a simple test app, I verified that data could be sent to the cloud using the driver and a response was received.

Dev branch [here](https://github.com/atharvanan1/aesd_linux_app/tree/azure)
